sudo: false

language: go

go:
  - "1.9"
  - "1.10"
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

before_script:
  - goimports -l ./ | xargs -r false
  - go vet ./...
  - golint ./... | xargs -r false

script:
  - go test -v ./...
